### PR TITLE
Fix hip-clang compilation error.

### PR DESCRIPTION
**Pull request by mhbliao**
- Need to include <functinoal> explicitly.
- Need to replace `__attribute__((cpu))` with `__host__`.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Thanks @amdkila , can this be cherry-picked into `master` branch or `master-rocm-2.6` branch?

**Comment by mhbliao** [comment]
could you please merge this into 'master' branch as well. it's urgent as it currently block the centos ci.

**Comment by saadrahim** [comment]
That can be done by end of day. We have some other updates we are planning to add. Is that reasonable?

**Comment by mhbliao** [comment]
ok, that sounds good.

**Pull request merged**
