### PR TITLE
Merging Develop to Master for rocm-2.1 

### PR DESCRIPTION
**Pull request by saadrahim**
Need to branch for QA testing of rocm-2.1. Are there any concerns with this? I can base of the current master but it may be worth while to include the changes.

### CODE REVIEW

**Comment by ex-rzr** [comment]
Why was the mode set to "Squash and merge" instead of "Create a merge commit"?

**Comment by ex-rzr** [comment]
Weird, GitHub sets it to "Squash and merge" again when I reload the page. Any ideas why?

**Comment by saadrahim** [comment]
> Why was the mode set to "Squash and merge" instead of "Create a merge commit"?

I was just checking what merge options were available. I didn't want to make another squash mistake. Weird that it even saved when I pulled the drop down. I don't intent to repeat a the mistake on rocPRIM>

**Comment by ex-rzr** [comment]
Yeah, very confusing :/ I will consider this strange GitHub's behavior in the future.

**Pull request merged**
