### PR TITLE
Standardizing include path to include the library name

### PR DESCRIPTION
**Pull request by saadrahim**
rocrand used to install to /opt/rocm/include/rocrand and /opt/rocm/include/hiprand
After switching to rocm-cmake, rocrand would place all the headers in /opt/rocm/include without the directories.
These changes restore that behavior with rocm-cmake.

### CODE REVIEW

**Comment by saadrahim** [comment]
This issue is blocking 2.6 testing. A quick turn around is needed.

**Comment by ex-rzr** [comment]
Initially paths like `/opt/rocm/include/hiprand_kernel.h` were supposed to mimic cuRAND's paths like `/opt/cuda/include/curand_kernel.h`.

IIRC, rocFFT also places its headers in `/opt/rocm/include/` without subdirs.

What reason to change the current behavior and why is this blocking?

**Comment by ex-rzr** [comment]
```
In file included from /builds/amd/rocRAND/library/src/rocrand.cpp:23:
In file included from /builds/amd/rocRAND/library/src/rng/generators.hpp:24:
In file included from /builds/amd/rocRAND/library/src/rng/philox4x32_10.hpp:59:
/builds/amd/rocRAND/library/include/rocrand/rocrand.h:39:10: fatal error: 'rocrand_version.h' file not found
#include "rocrand_version.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /builds/amd/rocRAND/library/src/rocrand.cpp:23:
In file included from /builds/amd/rocRAND/library/src/rng/generators.hpp:24:
In file included from /builds/amd/rocRAND/library/src/rng/philox4x32_10.hpp:59:
/builds/amd/rocRAND/library/include/rocrand/rocrand.h:39:10: fatal error: 'rocrand_version.h' file not found
#include "rocrand_version.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by saadrahim** [comment]
On the AMD side, we have no CI for this library. I am adding CI today but it will be helpful if you can confirm tests are passing.

**Comment by ex-rzr** [comment]
hipRAND-nvcc is broken:
```
/builds/amd/rocRAND/library/src/hiprand/hiprand_nvcc.cpp:25:21: fatal error: hiprand.h: No such file or directory
compilation terminated.
```

Statistical tests too:
```
/builds/amd/rocRAND/test/crush/crush_test_rocrand.cpp:32:10: fatal error: 'rocrand.h' file not found
#include <rocrand.h>
         ^~~~~~~~~~~
...
/builds/amd/rocRAND/test/crush/stat_test_rocrand_generate.cpp:32:10: fatal error: 'rocrand.h' file not found
#include <rocrand.h>
         ^~~~~~~~~~~
...
```

I think we are wasting our time working this way (too large latency between your changes and results of building on our end :/ ).

I can do this, but if you say so (otherwise we will do the same work twice).

Also could you answer my question in my previous message? I wonder why this is required.

**Comment by saadrahim** [comment]
Hi Anton,

Please finish it then. The main reason is to have the same file structure in /opt/rocm/install as the last release. Changing to rocm cmake caused these changes to install location.

I made changes to based on my interpretation of easiest method to implement.

I also did not consider the cuda path. Do you have ci for cuda as well.

Saad

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by saadrahim** [comment]
Also useful to learn you have additional tests in crush folder.

Saad

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ex-rzr** [comment]
Ok, I fixed some other header paths and also changed paths in CMake install() so there are  no empty hiprand in /opt/rocm/rocrand/include/ and vice versa like this:
```
/opt/rocm/rocrand/include/hiprand
/opt/rocm/rocrand/include/rocrand
/opt/rocm/rocrand/include/rocrand/rocrand.h
...
```

**Comment by ex-rzr** [comment]
> I also did not consider the cuda path. Do you have ci for cuda as well.

Yes, we test rocRAND (also hipCUB) on NVidia TitanV and 980. And of course on 3 ROCm supported AMD GPUs: 803, 900, 906.

**Pull request merged**
