### PR TITLE
Simplify convoluted vector indexing

### PR DESCRIPTION
**Pull request by AlexVlx**
Clang native vector types support indexing, and HIP vector types expose a `::data` member which represents the underlying native vector, so we might as well use it.

### CODE REVIEW

**Comment by ex-rzr** [comment]
So, you revert this change https://github.com/ROCmSoftwarePlatform/rocRAND/issues/32
1. How does it affect performance?
2. This change won't work on CUDA.

**Comment by AlexVlx** [comment]
No idea about that change, it's very interesting indeed. Performance is neutral at worst, as it actually saves on a needless min calculation associated with the switch. Last time I checked this is primarily AMD SW, so I have to admit lacking any particular interest in CUDA. Not sure if NV is investing in maintaining rocRAND for CUDA either but... different kettle of fish. TL;DR I expect that the macro guarded version will work there as well.

**Comment by ex-rzr** [comment]
`make benchmark_rocrand_kernel && benchmark/benchmark_rocrand_kernel --engine philox`

`uniform-uint`

Was:
```
gfx900
      Throughput =  292.590 GB/s, Samples =   73.147 GSample/s, AvgTime (1 trial) =    1.709 ms, Time (all) =   34.178 ms, Size = 134217728

gfx803
      Throughput =  151.476 GB/s, Samples =   37.869 GSample/s, AvgTime (1 trial) =    3.301 ms, Time (all) =   66.017 ms, Size = 134217728

gfx906
      Throughput =  228.957 GB/s, Samples =   57.239 GSample/s, AvgTime (1 trial) =    2.184 ms, Time (all) =   43.676 ms, Size = 134217728
```

Now:
```
gfx900
      Throughput =  356.857 GB/s, Samples =   89.214 GSample/s, AvgTime (1 trial) =    1.401 ms, Time (all) =   28.022 ms, Size = 134217728

gfx803
      Throughput =  183.153 GB/s, Samples =   45.788 GSample/s, AvgTime (1 trial) =    2.730 ms, Time (all) =   54.599 ms, Size = 134217728

gfx906
      Throughput =  267.255 GB/s, Samples =   66.814 GSample/s, AvgTime (1 trial) =    1.871 ms, Time (all) =   37.417 ms, Size = 134217728
```

So this change improves performance (I suppose, to performance before that workaround with switch in #32).

Can we rely on the `data` field (that it won't become private, renamed etc.)?

**Comment by AlexVlx** [comment]
Should be safe, no vector type changes incoming anytime soon, if ever.

**Comment by ex-rzr** [comment]
I've changed the target branch to `develop` (`develop_stream` is supposed to be a branch for merging changes from our private repo).

**NOTE: We should merge it using squashing**

**Pull request merged**
