### PR TITLE
Enable using hipcc as the CXX compiler

### PR DESCRIPTION
**Pull request by aaronenyeshi**
If we're using HIP-Clang to compile, we can allow the hipcc as CXX compiler.

### CODE REVIEW

**Comment by jszuppe** [comment]
Did you try building rocRAND using hipcc on ROCm platform?

**Comment by aaronenyeshi** [comment]
Yes, it builds with CXX=/opt/rocm/hip/bin/hipcc option added to cmake command. It builds fine, but running into a 19 of 26 test failures on HIP-Clang. We are working on a fix, and will make a PR for that

**Comment by jszuppe** [comment]
> Yes, it builds with CXX=/opt/rocm/hip/bin/hipcc option added to cmake command.

ok, in that case: LGTM, I'll merge in 10 minutes.

> PR for that

This PR will be for rocRAND or for HIP-Clang?

**Comment by aaronenyeshi** [comment]
Still investigating root cause, but more likely for HIP-Clang

**Pull request merged**
