### PR TITLE
Develop Stream 2022-11-14

### PR DESCRIPTION
**Pull request by nolmoonen**
- New generators phase two (of two):
    - Mersenne Twister pseudorandom number generator: MT19937.
    - Threefry pseudorandom number generators: Threefry2x32, Threefry2x64, Threefry4x32, and Threefry4x64.
- Tests and benchmarks for the new generators.
- Experimental HIP-CPU support: updates to build scripts, CI scripts, and minor code changes. Most notable code changes are a `reinterpret_cast` for the data pointer in `hipMalloc` and the deprecation of old-style predefined variables e.g. `threadIdx.x` in favor of `hipThreadIdx_x`.
- Ordering API interface (e.g. `ROCRAND_ORDERING_PSEUDO_DEFAULT`), but no backend support yet.
- Completed the port of the benchmarks to the Google Benchmark library: added `benchmark_rocrand_device_api.cpp`, `benchmark_curand_device_api.cpp`, and `benchmark_curand_host_api.cpp`. `benchmark_rocrand_host_api.cpp` was added in a previous PR.
- Removed references to Python 2.7, but no changes are made to break 2.7 support.
- Fixed `test/test_rocrand_sobol64_qrng.cpp` testing wrong engine type.
- Fixed missing default dimension for Sobol C++ wrapper engines in `rocrand.hpp`.
- Fixed kernel benchmark using wrong state type for scrambled Sobol. This change had virtually no impact on performance as the scrambled and normal Sobol perform almost the same.
- Fixed hipRAND build when `BUILD_HIPRAND=ON` on NVCC targets. Required due to the introduction of the `BUILD_WITH_LIB=CUDA` variable in hipRAND.
- Fixed compiler warning in LFSR113 on NVCC targets.
- Fixed Sobol64 using only the lower 32 bits of the produced 64 bits in the Poisson distribution. The engine now uses the full 64 bits to produce the 32-bits Poisson distributed numbers. No noticeable regression.
- Removed `-mf16c` flags from builds as it causes problems with `ulonglong4` used in Threefry4x64, but provides no additional benefit.

### CODE REVIEW

**Comment by Snektron** [comment]
Added commits related to the documentation

**Comment by stanleytsang-amd** [comment]
@nolmoonen @Snektron 
Test failure on CI:
44/44 Test #44: test_hiprand_linkage ....................***Failed    0.03 sec

Running main() from /tmp/grpc/googletest-release-1.11.0/googletest/src/gtest_main.cc

[==========] Running 1 test from 1 test suite.

[----------] Global test environment set-up.

[----------] 1 test from hiprand_linkage_tests

[ RUN      ] hiprand_linkage_tests.get_version_test

../../../../../hipRAND/test/linkage/test_hiprand_linkage.cpp:35: Failure

Expected equality of these values:

  get_hiprand_version()

    Which is: 201016

  201009

[  FAILED  ] hiprand_linkage_tests.get_version_test (0 ms)

[----------] 1 test from hiprand_linkage_tests (0 ms total)



[----------] Global test environment tear-down

[==========] 1 test from 1 test suite ran. (0 ms total)

[  PASSED  ] 0 tests.

[  FAILED  ] 1 test, listed below:

[  FAILED  ] hiprand_linkage_tests.get_version_test



 1 FAILED TEST

**Comment by stanleytsang-amd** [comment]
Also appears to be a single build failure in Windows:

[2022-12-08T16:00:19.644Z] [72/119] Linking CXX executable test\test_rocrand_kernel_scrambled_sobol64.exe

[2022-12-08T16:00:19.644Z] FAILED: test/test_rocrand_kernel_scrambled_sobol64.exe 

[2022-12-08T16:00:19.644Z] cmd.exe /C "cd . && c:\hip\bin\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -Ic:/hip/include -DWIN32 -D_CRT_SECURE_NO_WARNINGS -std=c++14 -fms-extensions -fms-compatibility -Wno-ignored-attributes -I/include/hip -D__HIP_PLATFORM_HCC__ -D__HIP_ROCclr__ -DHIP_CLANG_HCC_COMPAT_MODE=1 -Ic:/hip/include -DWIN32 -D_CRT_SECURE_NO_WARNINGS -std=c++14 -fms-extensions -fms-compatibility -Wno-ignored-attributes -I/include/hip -D__HIP_PLATFORM_HCC__ -D__HIP_ROCclr__ -DHIP_CLANG_HCC_COMPAT_MODE=1 -Wall -Wextra -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -Xlinker /subsystem:console test/CMakeFiles/test_rocrand_kernel_scrambled_sobol64.dir/test_rocrand_kernel_scrambled_sobol64.cpp.obj -o test\test_rocrand_kernel_scrambled_sobol64.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:test\test_rocrand_kernel_scrambled_sobol64.lib -Xlinker /pdb:test\test_rocrand_kernel_scrambled_sobol64.pdb -Xlinker /version:0.0   library/rocrand.lib  C:/github/vcpkg/installed/x64-windows/lib/manual-link/gtest_main.lib  C:/github/vcpkg/installed/x64-windows/lib/gtest.lib  c:/hip/lib/amdhip64.lib  --hip-link  --offload-arch=gfx906  --offload-arch=gfx1030  --offload-arch=gfx1100  --offload-arch=gfx1101  --offload-arch=gfx1102  C:/hip/lib/clang/16.0.0/lib/windows/clang_rt.builtins-x86_64.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cmd.exe /C "cd /D C:\jenkins\workspace\rocmmathlib_rocrand_pr-300\build\release\test && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/github/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/jenkins/workspace/rocmmathlib_rocrand_pr-300/build/release/test/test_rocrand_kernel_scrambled_sobol64.exe -installedDir C:/github/vcpkg/installed/x64-windows/bin -OutVariable out""

[2022-12-08T16:00:19.644Z] lld-link: error: undefined symbol: unsigned __int64 const *const rocrand_h_scrambled_sobol64_direction_vectors

[2022-12-08T16:00:19.644Z] >>> referenced by test/CMakeFiles/test_rocrand_kernel_scrambled_sobol64.dir/test_rocrand_kernel_scrambled_sobol64.cpp.obj:(void __cdecl load_scrambled_sobol64_constants_to_gpu(unsigned int, unsigned __int64 **, unsigned __int64 **))

**Comment by Snektron** [comment]
@stanleytsang-amd pushed a fix to https://github.com/ROCmSoftwarePlatform/hipRAND/pull/24 that should resolve the version issue

**Pull request merged**
