### PR TITLE
Revert "Standardize include path to include the library name (#60)"

### PR DESCRIPTION
**Pull request by yoichiyoshida**
Reverts ROCmSoftwarePlatform/rocRAND#62
This change breaks upstream projects PyTorch and Caffe2. Reverting breaking change until a fix is available.

### CODE REVIEW

**Comment by ex-rzr** [comment]
Maybe it's better to reset the branch to the previous commit? There are no branches based on the current master: https://github.com/ROCmSoftwarePlatform/rocRAND/network

**Comment by saadrahim** [comment]
Did we go back far enough that Tensorflow will not have a problem? Starting to use rocm-cmake started this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yoichiyoshida** [comment]
I can reset the branch back to 2.5, which is before rocm-cmake. There is one branch in between by Akila, but hopefully that is minor enough that it can be recreated.

**Comment by VincentSC** [comment]
Please hold any action untill it is fully clear what's the problem. The reason for #60 was to standardize the location for the ROCm libraries. If now something breaks, then probably that has to be fixed, not?

Can you explain why you want to revert? What is going wrong exactly? What are we missing?

**Comment by yoichiyoshida** [comment]
The new standardized location is different than the location for most of the other projects at the moment. It's too close to release to ask upstream projects to arbitrarily change their paths without communication. #60/62 breaks PyTorch (but fixes Tensorflow), and #58/59 breaks Tensorflow, so the plan is to roll it back to before those two so both upstream projects stay working for this release (ie. back to 2.5). After the 2.6 release these changes can be revisited so that both upstream projects can be made to work.

**Pull request merged**
