### PR TITLE
Develop 164 tests

### PR DESCRIPTION
**Pull request by arsenm**
I think this should be included in the main set of tests to avoid future regressions

### CODE REVIEW

**Comment by jszuppe** [comment]
I think we should remove `std::cout`s from the test.

**Comment by jszuppe** [comment]
Also isn't it more test for hcc/ROCm and not for rocRAND? Maybe we shouldn't put tests for compiler into RNG library?

Your commit looks good and doesn't require a discussion, so you can make a separate pull request for that one if you want to have that one in `master` already.

**Comment by bragadeesh** [comment]
@arsenm can you issue the PR to go into develop_164_tests branch; let's discuss separately how to incorporate this testing in hcc  
@jszuppe what @arsenm is asking to do is to not use inline asm for reading the exec register; instead use the built-in intrinsic;

**Comment by jszuppe** [comment]
> @arsenm can you issue the PR to go into develop_164_tests branch; let's discuss separately how to incorporate this testing in hcc

@arsenm already pushed his commits into `develop_164_tests`. This pull request is not from his private fork, but from `develop_164_tests` to `master`.

> @jszuppe what @arsenm is asking to do is to not use inline asm for reading the exec register; instead use the built-in intrinsic;

Sure, we will do that in future. I guess that was the fastest way my colleague knew how to extract values of the exec register at that moment. Also, that test was just to provide minimal test case. By the way, if you want to put that into `hcc` test suite the only dependency on rocRAND is `rocrand_xorwow_precomputed.h`.  I suppose it can be replace by a matrix right in the file with the test (something like `d_xorwow_sequence_jump_matrices[10][800] = { 1234567 };`)

**Pull request closed without merging**
